name: todoapp
description: Todoapp
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.1

dependencies:
  appwrite: ^8.3.0
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  provider: ^6.0.1
  
  flutter_localizations:
  
    sdk: flutter
  intl: ^0.17.0
  shared_preferences: ^2.1.1
  image_picker: ^0.8.7+5

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
